### ISSUE TITLE
US 02.04.01 - Implement ability to view details of a Recipe

### ISSUE THREAD

**Issue by tylers-ualberta** [CMPUT301F22T15/Foodverse#13]
Users should be able to view a recipe's details.

- [x] Create UI for viewing details

**Comment by AaronL-Ualberta** [comment]
Maybe we should make a consistent layout for viewing recipes, ingredients, and meals to make a more unified user experience.

**Comment by acharyarucha** [comment]
Idea is to have the user be able to click on a recipe item which will open a dialog fragment - this will be the interface that allows user to view the details.

**Comment by acharyarucha** [comment]
This feature has been implemented. Changes just need to be pushed
