### ISSUE TITLE
Comments for Project Part 2

### ISSUE THREAD

**Issue by hamzaMAlvi** [CMPUT301F22T15/Foodverse#52]
#### If necessary make new issues relevant to the comments and link them to this issue (make them a subtask of this issue). If you have any confusion mention me in the comments section of this issue along with the question.
---

@Ppatel122 @tylers-ualberta @AaronL-Ualberta @acharyarucha @ethanfranz7 @choff2 

---
### Marks
3/3
### Comments
Some things can be improved in using the tools. Ask TA regarding this matter.

- [x] No action needed at this time.

---

### Marks
3/3
### Comments
✓ Requirements are very comprehensive and thoroughly tracked and organized, great work!
✓ Requirements noted for half-way checkpoint
✓ Story point estimates are complete and well assigned
✓ Risk level estimates are complete and well assigned (however, I would recommend renaming them from ""Priority"" to ""Risk"" to avoid confusion)

- [x] Rename Priority to Risk

---

### Marks
3/3
### Comments
1. View App is in the collaborator list but it is not stated as a separate card.
2.  Class name contains space like ""Meal Plan"". Follow the naming convention.
• Clear, readable, consistent, and organized: See comments
• Covers key classes: Yes
• Complete responsibilities: Yes
• Complete collaborators: Yes
• Object-oriented: Yes
• Cohesive classes: Yes
• Coupling managed: Yes

- [x] #55

---

### Marks
3/3
### Comments
• Consistent and clear: yes
• Complete UI mockups: yes, where is the main landing page
• Labeled elements on UI mockups: yes
• Detailed storyboard: yes
• Labeled actions for storyboard transitions: yes
• Covers all requirements: yes
• Intuitive user interface: mostly, make the UI user friendly and intuitive, everything looks clutered
• Displays understanding of UI mockups and storyboarding: yes
Ask the TA in the next meeting for detailed list of improvements that can be made

- [x] #54

**Comment by hamzaMAlvi** [comment]
Please give me permissions owner permissions to the repo, so I can use the complete set of functionalities provided by GitHub.

**Comment by tylers-ualberta** [comment]
@hamzaMAlvi You should have owner permissions now, please let us know if there are any other issues with the permissions.

**Comment by tylers-ualberta** [comment]
Updated repository based on comments.
