### ISSUE TITLE
US 02.01.01 - Implement ability to create a Recipe

### ISSUE THREAD

**Issue by tylers-ualberta** [CMPUT301F22T15/Foodverse#7]
Users should be able to add recipes with a title, prep time, servings, category, comments, a picture and a list of ingredients.

- [ ] Create UI for adding recipes
- [ ] Implement recipe class
- [ ] Implement storage of created recipes

**Comment by choff2** [comment]
The ingredients added to the list should be of the Ingredient class, not the OwnedIngredient class.
