### ISSUE TITLE
US 01.02.01 - Create an interface to view details for OwnedIngredients

### ISSUE THREAD

**Issue by ethanfranz7** [CMPUT301F22T15/Foodverse#9]
As a meal planner, I want to view an ingredient and its details.

- [x] Create UI for detail viewing
- [x] Implement population from existing ingredient

**Comment by tylers-ualberta** [comment]
I assigned Aaron since his code for US 01.01.01, US 01.03.01, US 01.04.01 and US 01.05.01 also handles this.
